### ISSUE TITLE
Calendar bug

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#122] opened 2015-05-04 20:47 UTC
If you click Next Event from the last event on the site, the system goes back in time and shows a Free Day from January:
https://clyffordstillmuseum.org/%3Fpost_type%3Dtribe_events%26p%3D3352

**Comment by halfempty** [comment] 2015-06-01 21:25
@swambold6 It looks like the issue is actually with it being a recurring event. All instances of that Free Day recurrence are resolving incorectly. I've posted to their forum.

(I'm no longer a fan of this ECP plugin. Too unstable/buggy.)

**Comment by swambold6** [comment] 2015-06-01 21:53
We're using this for CU South Denver:

http://wp-event-organiser.com/

Will let you know what I think of it as I start working with it.



On Mon, Jun 1, 2015 at 3:25 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @swambold6 <https://github.com/swambold6> It looks like the issue is
> actually with it being a recurring event. All instances of that Free Day
> recurrence are resolving incorectly. I've posted to their forum.
>
> (I'm no longer a fan of this ECP plugin. Too unstable/buggy.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/122#issuecomment-107717328>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment] 2015-06-17 19:56
Okay, I think this is fixed now.

**Closed by halfempty** 2015-06-17 19:56 UTC
Labels: bug
